language: r
sudo: false
cache: packages

warnings_are_errors: true
bioc_required: true

r_packages:
  - covr

bioc_packages:
  - BiocStyle
  - BRAIN
  - UniProt.ws

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
