language: r
warnings_are_errors: true
bioc_required: true

r_github_packages:
  - jimhester/covr

r_binary_packages:
  - testthat
  - knitr

bioc_packages:
  - BiocStyle
  - BRAIN
  - UniProt.ws

after_success:
  - Rscript -e 'library(covr);codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
